services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: burn-style_backend
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port ${API_PORT} --reload
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    volumes:
      - ./backend/alembic:/app/alembic
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
        - action: rebuild
          path: ./backend/pyproject.toml
        - action: rebuild
          path: ./backend/uv.lock
        - action: rebuild
          path: ./backend/Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: burn-style_frontend
    command: npx vite --host 0.0.0.0 --port ${FRONTEND_PORT}
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync
          path: ./frontend/public
          target: /app/public
        - action: sync
          path: ./frontend/index.html
          target: /app/index.html
        - action: rebuild
          path: ./frontend/package.json

  db:
    build:
      context: ./db
      dockerfile: Dockerfile.db
    container_name: burn-style_db
    command: -p ${POSTGRES_PORT}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
