"""initial

Revision ID: 314e2e8e782a
Revises: 
Create Date: 2026-02-15 18:30:56.276478

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "314e2e8e782a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("categories",
    sa.Column("uuid", sa.String(length=32), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table("expenses",
    sa.Column("uuid", sa.String(length=32), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("amount", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("deleted_at", sa.DateTime(), nullable=True),
    sa.CheckConstraint("amount > 0", name="check_amount_positive"),
    sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table("expense_category_association",
    sa.Column("expense_uuid", sa.String(length=32), nullable=False),
    sa.Column("category_uuid", sa.String(length=32), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(["category_uuid"], ["categories.uuid"] ),
    sa.ForeignKeyConstraint(["expense_uuid"], ["expenses.uuid"] ),
    sa.PrimaryKeyConstraint("expense_uuid", "category_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expense_category_association")
    op.drop_table("expenses")
    op.drop_table("categories")
    # ### end Alembic commands ###
