"""initial

Revision ID: e5265a03359c
Revises: 
Create Date: 2025-12-21 18:49:40.748090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5265a03359c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('transactions',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('transaction_category_association',
    sa.Column('transaction_uuid', sa.String(length=32), nullable=False),
    sa.Column('category_uuid', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['category_uuid'], ['categories.uuid'], ),
    sa.ForeignKeyConstraint(['transaction_uuid'], ['transactions.uuid'], ),
    sa.PrimaryKeyConstraint('transaction_uuid', 'category_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_category_association')
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('categories')
    # ### end Alembic commands ###
