"""initial

Revision ID: 2497e50b8efc
Revises:
Create Date: 2026-02-23 22:50:25.094425

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2497e50b8efc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("uuid", sa.String(length=32), nullable=False),
    sa.Column("username", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("uuid"),
    sa.UniqueConstraint("username"),
    )
    op.create_table("categories",
    sa.Column("uuid", sa.String(length=32), nullable=False),
    sa.Column("user_uuid", sa.String(length=32), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(["user_uuid"], ["users.uuid"] ),
    sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table("expenses",
    sa.Column("uuid", sa.String(length=32), nullable=False),
    sa.Column("user_uuid", sa.String(length=32), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("amount", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("deleted_at", sa.DateTime(), nullable=True),
    sa.CheckConstraint("amount > 0", name="check_amount_positive"),
    sa.ForeignKeyConstraint(["user_uuid"], ["users.uuid"] ),
    sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table("webauthn_credentials",
    sa.Column("uuid", sa.String(length=32), nullable=False),
    sa.Column("user_uuid", sa.String(length=32), nullable=False),
    sa.Column("credential_id", sa.LargeBinary(), nullable=False),
    sa.Column("credential_public_key", sa.LargeBinary(), nullable=False),
    sa.Column("sign_count", sa.Integer(), nullable=False),
    sa.Column("transports", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(["user_uuid"], ["users.uuid"] ),
    sa.PrimaryKeyConstraint("uuid"),
    sa.UniqueConstraint("credential_id"),
    )
    op.create_table("expense_category_association",
    sa.Column("expense_uuid", sa.String(length=32), nullable=False),
    sa.Column("category_uuid", sa.String(length=32), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(["category_uuid"], ["categories.uuid"] ),
    sa.ForeignKeyConstraint(["expense_uuid"], ["expenses.uuid"] ),
    sa.PrimaryKeyConstraint("expense_uuid", "category_uuid"),
    )
    op.create_table("subscription_templates",
    sa.Column("uuid", sa.String(length=32), nullable=False),
    sa.Column("user_uuid", sa.String(length=32), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("amount", sa.Integer(), nullable=False),
    sa.Column("category_uuid", sa.String(length=32), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("deleted_at", sa.DateTime(), nullable=True),
    sa.CheckConstraint("amount > 0", name="check_subscription_amount_positive"),
    sa.ForeignKeyConstraint(["category_uuid"], ["categories.uuid"] ),
    sa.ForeignKeyConstraint(["user_uuid"], ["users.uuid"] ),
    sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription_templates")
    op.drop_table("expense_category_association")
    op.drop_table("webauthn_credentials")
    op.drop_table("expenses")
    op.drop_table("categories")
    op.drop_table("users")
    # ### end Alembic commands ###
