"""add_webauthn_challenges

Revision ID: 4b55d17ee529
Revises: a1b2c3d4e5f6
Create Date: 2026-05-12 08:34:12.215575

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b55d17ee529"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("webauthn_challenges",
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("challenge", sa.LargeBinary(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("webauthn_challenges")
    # ### end Alembic commands ###
