"""add_expensed_at_to_expenses

Revision ID: e345bb132e9a
Revises: 9ca611086cef
Create Date: 2026-03-21 12:09:18.170167

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e345bb132e9a"
down_revision: str | Sequence[str] | None = "9ca611086cef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("expensed_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenses", "expensed_at")
    # ### end Alembic commands ###
