"""subscription_templatesテーブル追加

Revision ID: eccde9337361
Revises: 45af332485ef
Create Date: 2026-02-23 16:16:26.757317

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eccde9337361"
down_revision: str | Sequence[str] | None = "45af332485ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("subscription_templates",
    sa.Column("uuid", sa.String(length=32), nullable=False),
    sa.Column("user_uuid", sa.String(length=32), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("amount", sa.Integer(), nullable=False),
    sa.Column("category_uuid", sa.String(length=32), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("deleted_at", sa.DateTime(), nullable=True),
    sa.CheckConstraint("amount > 0", name="check_subscription_amount_positive"),
    sa.ForeignKeyConstraint(["category_uuid"], ["categories.uuid"] ),
    sa.ForeignKeyConstraint(["user_uuid"], ["users.uuid"] ),
    sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription_templates")
    # ### end Alembic commands ###
