name: Deploy Backend

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "backend/.python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: cd backend && uv sync --all-groups

      - name: mypy
        run: cd backend && uv run mypy .

      - name: ruff
        run: cd backend && uv run ruff check .

      - name: test
        run: cd backend && uv run pytest -v

  deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "backend/.python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install dependencies
        if: inputs.environment == 'production'
        run: cd backend && uv sync --all-groups

      - name: Run database migrations
        if: inputs.environment == 'production'
        env:
          VERCEL_ENV: production
        run: |
          cd backend
          vercel env pull .env.production --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          set -a
          . .env.production
          set +a
          uv run alembic upgrade head

      - name: Build
        run: vercel build ${{ inputs.environment == 'production' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        run: vercel deploy --prebuilt ${{ inputs.environment == 'production' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}
